apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: psql-{{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:3.1
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: '{{ .Values.pgadmin.email }}'
        - name: PGADMIN_DEFAULT_PASSWORD
          value: '{{ .Values.pgadmin.password }}'
        - name: PGADMIN_PORT
          value: '80'
