apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: psql-{{ .Release.Name }}
spec:
  selector:
    app: pgadmin
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
