apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: az-postgresql-volume
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi