apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: az-postgresql-volume
  namespace:  "{{ .Release.Name }}"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 5Gi