apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgtesql
  namespace:  {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: az-postgresql-volume
      containers:
      - name: postgresql
        image: postgres:10.4-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "{{ .Values.postgresql.username }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.postgresql.password }}"
        - name: POSTGRES_DB
          value: "{{ .Values.postgresql.dbname }}"
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql

        
