apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace:  "{{ .Release.Name }}"
spec:
  selector:
    app: pgadmin
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
