apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace:  {{ .Release.Name }}
spec:
  selector:
    app: postgresql
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
